apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpserver-app
  name: httpserver-app
  namespace: webservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpserver-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      creationTimestamp: null
      labels:
        app: httpserver-app
    spec:
      containers:
      - image: brian880120/cncampa04-httpserver-metrics:v1
        name: httpserver
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: httpserver-config
              key: PORT
        volumeMounts:
        - mountPath: /var/log
          name: log-volume
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo Hello from the port: ${PORT} > /usr/share/message"]
        resources:
          limits:
            cpu: 700m
            memory: 200Mi
          requests:
            cpu: 500m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 8080
      restartPolicy: Always
      volumes:
      - name: log-volume
        emptyDir: {}
status: {}
